version: '3'
services:
  worker:
    build: ./worker
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=DLMS
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
  api:
    build: ./api
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=DLMS
    ports:
      - '8000:8000'
  ui:
    build: ./ui
    depends_on:
      - api
    ports:
      - '3000:3000'
  mongo:
    image: 'mongo:4.1'
    ports:
      - '27017:27017'
  rabbitmq:
    image: 'rabbitmq:3.7-management'
    ports:
      - '15672:15672'
      - '5672:5672'
