version: '3'
services:
  backend:
    image: 'node:11-alpine'
    working_dir: /usr/src/app
    command: npm run watch
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=DLMS
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '8000:8000'
  ui:
    build: ./ui
    depends_on:
      - backend
    ports:
      - '3000:3000'
  mongo:
    image: 'mongo:4.1'
    ports:
      - '27017:27017'
  rabbitmq:
    image: 'rabbitmq:3.7-management'
    ports:
      - '15672:15672'
      - '5672:5672'
